export type Starter = {
  id: string;
  edition: "state" | "country" | "globe";
  regionId: string;
  name: string;
  lon: number;
  lat: number;
  story: string;
  sourceLabel: string;
  sourceHref: string;
};

function place(
  edition: Starter["edition"],
  regionId: string,
  slug: string,
  name: string,
  lon: number,
  lat: number,
  story: string,
  wiki: string,
): Starter {
  return {
    id: `${regionId}-${slug}`,
    edition,
    regionId,
    name,
    lon,
    lat,
    story,
    sourceLabel: "Wikipedia",
    sourceHref: `https://en.wikipedia.org/wiki/${wiki}`,
  };
}

export const STARTERS: Starter[] = [
  place(
    "state",
    "alabama",
    "vulcan",
    "Vulcan Park",
    -86.795,
    33.491,
    "The iron Vulcan stands on Red Mountain above Birmingham. Cast for a world's fair, the statue still looks over the city it was built to advertise.",
    "Vulcan_statue",
  ),
  place(
    "state",
    "alabama",
    "capitol",
    "Alabama State Capitol",
    -86.301,
    32.377,
    "A white dome marks the capitol on a hill in Montgomery. The Selma voting-rights march ended on the steps below that dome.",
    "Alabama_State_Capitol",
  ),
  place(
    "state",
    "alabama",
    "uss-alabama",
    "USS Alabama",
    -88.015,
    30.682,
    "A gray battleship is moored in Mobile Bay at a waterfront park. Visitors walk the decks of a ship that fought in the Second World War.",
    "USS_Alabama_(BB-60)",
  ),
  place(
    "state",
    "alabama",
    "rocket-center",
    "US Space and Rocket Center",
    -86.655,
    34.711,
    "Rockets stand in an open field on the edge of Huntsville. The center grew up beside the engineers who built the Saturn moon rocket.",
    "U.S._Space_%26_Rocket_Center",
  ),
  place(
    "state",
    "alabama",
    "cheaha",
    "Cheaha Mountain",
    -85.809,
    33.486,
    "Cheaha Mountain is the highest point in Alabama, a quartzite knob in the Talladega range. On a clear day the ridge looks across a long stretch of forest.",
    "Cheaha_Mountain",
  ),
  place(
    "state",
    "alaska",
    "denali",
    "Denali",
    -151.007,
    63.069,
    "Denali is the highest peak in North America and the anchor of the Alaska Range. Clouds hide the summit more often than they reveal it.",
    "Denali",
  ),
  place(
    "state",
    "alaska",
    "glacier-bay",
    "Glacier Bay",
    -136.9,
    58.5,
    "Tidewater glaciers calve into the long fjords of Glacier Bay. The ice has retreated far up these inlets since the eighteenth century.",
    "Glacier_Bay_National_Park_and_Preserve",
  ),
  place(
    "state",
    "alaska",
    "fairbanks",
    "Fairbanks",
    -147.716,
    64.837,
    "Fairbanks sits on the Chena River in the Alaska interior. Winter nights here run long enough for the aurora to become ordinary.",
    "Fairbanks,_Alaska",
  ),
  place(
    "state",
    "alaska",
    "juneau",
    "Juneau",
    -134.42,
    58.301,
    "Juneau climbs a mountainside with no road to the rest of the state. Ferries and planes do the work a highway would do elsewhere.",
    "Juneau,_Alaska",
  ),
  place(
    "state",
    "alaska",
    "nome",
    "Nome",
    -165.406,
    64.501,
    "Nome faces the Bering Sea on the Seward Peninsula. The beach in front of town was a gold-rush shoreline at the end of the nineteenth century.",
    "Nome,_Alaska",
  ),
  place(
    "state",
    "arizona",
    "grand-canyon",
    "Grand Canyon",
    -112.113,
    36.062,
    "A gorge a mile deep cuts the Colorado Plateau in northern Arizona. The river at the bottom is the same Colorado that begins in the Rockies.",
    "Grand_Canyon",
  ),
  place(
    "state",
    "arizona",
    "horseshoe-bend",
    "Horseshoe Bend",
    -111.51,
    36.879,
    "The Colorado River loops in a tight curve under a sandstone rim near Page. The overlook is a short walk to the edge of that cliff.",
    "Horseshoe_Bend_(Arizona)",
  ),
  place(
    "state",
    "arizona",
    "cathedral-rock",
    "Cathedral Rock",
    -111.793,
    34.82,
    "Red rock buttes stand over Oak Creek at Cathedral Rock near Sedona. The stone is the same formation that colors the Mogollon Rim.",
    "Cathedral_Rock",
  ),
  place(
    "state",
    "arizona",
    "meteor-crater",
    "Meteor Crater",
    -111.023,
    35.027,
    "A bowl in the desert east of Flagstaff marks where an iron meteorite struck. The rim stays sharp because the dry climate preserves it.",
    "Meteor_Crater",
  ),
  place(
    "state",
    "arizona",
    "saguaro",
    "Saguaro National Park",
    -111.166,
    32.25,
    "Giant cacti cover the rocky slopes west of Tucson. A saguaro grows arms only after many decades in this hot valley.",
    "Saguaro_National_Park",
  ),
  place(
    "state",
    "arkansas",
    "bathhouse-row",
    "Bathhouse Row",
    -93.054,
    34.513,
    "Hot water rises under a row of historic bathhouses in downtown Hot Springs. People have come for these springs since long before the park was set aside.",
    "Bathhouse_Row",
  ),
  place(
    "state",
    "arkansas",
    "crater-of-diamonds",
    "Crater of Diamonds",
    -93.672,
    34.032,
    "A plowed volcanic field near Murfreesboro is open for public diamond hunting. Visitors keep whatever stones they find in the dirt.",
    "Crater_of_Diamonds_State_Park",
  ),
  place(
    "state",
    "arkansas",
    "blanchard-springs",
    "Blanchard Springs Caverns",
    -92.233,
    35.96,
    "A living cave drips under the Ozark forest near Mountain View. Tours follow rooms the public first entered in the twentieth century.",
    "Blanchard_Springs_Caverns",
  ),
  place(
    "state",
    "arkansas",
    "petit-jean",
    "Petit Jean State Park",
    -92.938,
    35.121,
    "Cedar Falls drops from a bluff in Petit Jean State Park. The mountain is a flat-topped remnant above the Arkansas River valley.",
    "Petit_Jean_State_Park",
  ),
  place(
    "state",
    "arkansas",
    "buffalo-river",
    "Buffalo National River",
    -92.817,
    35.985,
    "The Buffalo is a free-flowing river through the Ozark hills. Bluffs and gravel bars line a stream that was the first national river in the country.",
    "Buffalo_National_River",
  ),
  place(
    "state",
    "california",
    "yosemite",
    "Yosemite Valley",
    -119.594,
    37.745,
    "Granite walls close around the flat floor of Yosemite Valley. Waterfalls spill from the rim when the snow above begins to melt.",
    "Yosemite_Valley",
  ),
  place(
    "state",
    "california",
    "golden-gate",
    "Golden Gate Bridge",
    -122.478,
    37.819,
    "The red-orange span crosses the mouth of San Francisco Bay. Fog often covers the towers before it covers the city behind them.",
    "Golden_Gate_Bridge",
  ),
  place(
    "state",
    "california",
    "badwater",
    "Badwater Basin",
    -116.825,
    36.25,
    "Badwater Basin is the lowest ground in North America, a salt flat in Death Valley. Summer heat here is among the most extreme on the continent.",
    "Badwater_Basin",
  ),
  place(
    "state",
    "california",
    "whitney",
    "Mount Whitney",
    -118.292,
    36.578,
    "Mount Whitney is the highest peak in the contiguous United States. The east face rises abruptly above the Owens Valley.",
    "Mount_Whitney",
  ),
  place(
    "state",
    "california",
    "redwood",
    "Redwood National Park",
    -124.004,
    41.213,
    "Coast redwoods in this park are among the tallest living trees. The groves stand in fog that rolls inland off the Pacific.",
    "Redwood_National_and_State_Parks",
  ),
  place(
    "state",
    "colorado",
    "bear-lake",
    "Bear Lake",
    -105.648,
    40.313,
    "Bear Lake sits in a high cirque inside Rocky Mountain National Park. Trails from the shore climb toward the Continental Divide.",
    "Bear_Lake_(Colorado)",
  ),
  place(
    "state",
    "colorado",
    "cliff-palace",
    "Cliff Palace",
    -108.472,
    37.167,
    "Stone rooms fill a cliff alcove at Cliff Palace in Mesa Verde. The people who built them left the mesa centuries ago.",
    "Cliff_Palace",
  ),
  place(
    "state",
    "colorado",
    "great-sand-dunes",
    "Great Sand Dunes",
    -105.512,
    37.732,
    "A dune field piles against the Sangre de Cristo Mountains. Wind and a seasonal creek keep reshaping the sand.",
    "Great_Sand_Dunes_National_Park_and_Preserve",
  ),
  place(
    "state",
    "colorado",
    "pikes-peak",
    "Pikes Peak",
    -105.044,
    38.84,
    "Pikes Peak rises above Colorado Springs on the Front Range. Both a road and a railway reach the summit.",
    "Pikes_Peak",
  ),
  place(
    "state",
    "colorado",
    "garden-of-the-gods",
    "Garden of the Gods",
    -104.886,
    38.878,
    "Red sandstone fins stand on edge at the foot of Pikes Peak. The garden is a city park with the mountains for a backdrop.",
    "Garden_of_the_Gods",
  ),
  place(
    "state",
    "connecticut",
    "mystic",
    "Mystic Seaport",
    -71.966,
    41.364,
    "A waterfront museum in Mystic keeps a wooden whaling ship at the dock. The village around it shows how a nineteenth-century port was built.",
    "Mystic_Seaport",
  ),
  place(
    "state",
    "connecticut",
    "twain",
    "Mark Twain House",
    -72.701,
    41.767,
    "Mark Twain wrote his best-known novels in this Hartford house. The brick mansion is as odd and ornate as the books that paid for it.",
    "Mark_Twain_House",
  ),
  place(
    "state",
    "connecticut",
    "gillette",
    "Gillette Castle",
    -72.428,
    41.428,
    "An actor built a fieldstone castle on a bluff above the Connecticut River. The rooms are full of handmade locks and doors of unusual shapes.",
    "Gillette_Castle_State_Park",
  ),
  place(
    "state",
    "connecticut",
    "new-haven-green",
    "New Haven Green",
    -72.928,
    41.309,
    "A public green sits at the center of downtown New Haven. Three churches along one side face the old campus of Yale.",
    "New_Haven_Green",
  ),
  place(
    "state",
    "connecticut",
    "kent-falls",
    "Kent Falls",
    -73.431,
    41.778,
    "A brook drops in steps through a hemlock ravine at Kent Falls. The cascade is a short walk from a road that follows the Housatonic.",
    "Kent_Falls_State_Park",
  ),
  place(
    "state",
    "delaware",
    "wilmington",
    "Wilmington",
    -75.54,
    39.739,
    "Wilmington is the largest city in Delaware and sits where the Christina meets the tide. Ships can still reach its harbor from Delaware Bay.",
    "Wilmington,_Delaware",
  ),
  place(
    "state",
    "delaware",
    "dover",
    "Dover",
    -75.524,
    39.158,
    "Dover is the capital of Delaware and the seat of a small downtown. The capitol green is a short walk from the old state house.",
    "Dover,_Delaware",
  ),
  place(
    "state",
    "delaware",
    "lewes",
    "Lewes",
    -75.139,
    38.775,
    "Lewes faces Delaware Bay where the bay meets the Atlantic. A lighthouse and a ferry terminal mark this old coastal town.",
    "Lewes,_Delaware",
  ),
  place(
    "state",
    "delaware",
    "bombay-hook",
    "Bombay Hook",
    -75.47,
    39.26,
    "Tidal marshes at Bombay Hook fill and empty with the Delaware Bay. Migrating shorebirds use the flats in huge numbers each spring and fall.",
    "Bombay_Hook_National_Wildlife_Refuge",
  ),
  place(
    "state",
    "delaware",
    "hagley",
    "Hagley Museum",
    -75.578,
    39.771,
    "Gunpowder mills once lined the Brandywine at Hagley. The stone workshops now show how the du Pont powder works got its start.",
    "Hagley_Museum_and_Library",
  ),
  place(
    "state",
    "florida",
    "anhinga",
    "Anhinga Trail",
    -80.608,
    25.382,
    "A boardwalk crosses a freshwater slough full of alligators and wading birds. This corner of the Everglades is a short drive from the suburbs of Miami.",
    "Everglades_National_Park",
  ),
  place(
    "state",
    "florida",
    "key-west",
    "Key West",
    -81.8,
    24.555,
    "Key West is the last sizable island in the Florida Keys. The town sits on low coral rock between the Atlantic and the Gulf.",
    "Key_West",
  ),
  place(
    "state",
    "florida",
    "kennedy",
    "Kennedy Space Center",
    -80.649,
    28.572,
    "Launch pads stand on a barrier island at Kennedy Space Center. Rockets leave the Florida coast from this stretch of Merritt Island.",
    "Kennedy_Space_Center",
  ),
  place(
    "state",
    "florida",
    "castillo",
    "Castillo de San Marcos",
    -81.312,
    29.898,
    "A coquina fort guards the water entrance to Saint Augustine. Spanish builders finished the star-shaped walls in the late seventeenth century.",
    "Castillo_de_San_Marcos",
  ),
  place(
    "state",
    "florida",
    "fort-jefferson",
    "Fort Jefferson",
    -82.873,
    24.628,
    "A brick fort sits on a tiny island about seventy miles west of Key West. Coral reef surrounds the walls, and a ferry is the usual way out.",
    "Dry_Tortugas_National_Park",
  ),
  place(
    "state",
    "georgia",
    "stone-mountain",
    "Stone Mountain",
    -84.146,
    33.806,
    "A granite dome rises just east of Atlanta. A large carving is cut into one face of the bare rock.",
    "Stone_Mountain",
  ),
  place(
    "state",
    "georgia",
    "savannah",
    "Savannah Historic District",
    -81.092,
    32.074,
    "Squares and live oaks organize the old center of Savannah. The riverfront below the bluff is still a working port.",
    "Savannah_Historic_District_(Savannah,_Georgia)",
  ),
  place(
    "state",
    "georgia",
    "okefenokee",
    "Okefenokee Swamp",
    -82.333,
    30.74,
    "The Okefenokee is a blackwater swamp of peat, cypress, and open prairie. Boardwalks and small boats are the ways through it.",
    "Okefenokee_Swamp",
  ),
  place(
    "state",
    "georgia",
    "cumberland",
    "Cumberland Island",
    -81.45,
    30.85,
    "Wild horses graze around a ruined mansion on Cumberland Island. The island is reached by ferry and has no bridge to the mainland.",
    "Cumberland_Island",
  ),
  place(
    "state",
    "georgia",
    "providence",
    "Providence Canyon",
    -84.919,
    32.064,
    "Soft hills near Lumpkin have eroded into pale pink gullies. The canyon is young, cut by farm runoff in the nineteenth century.",
    "Providence_Canyon_State_Park",
  ),
  place(
    "state",
    "hawaii",
    "kilauea",
    "Kilauea",
    -155.283,
    19.407,
    "Kilauea is an active volcano on the island of Hawaii. Lava from this crater has rebuilt the nearby coastline more than once in living memory.",
    "K%C4%ABlauea",
  ),
  place(
    "state",
    "hawaii",
    "diamond-head",
    "Diamond Head",
    -157.805,
    21.262,
    "Diamond Head is a tuff cone at the east end of Waikiki. A steep path climbs to the crater rim above the hotels.",
    "Diamond_Head,_Hawaii",
  ),
  place(
    "state",
    "hawaii",
    "haleakala",
    "Haleakala",
    -156.253,
    20.71,
    "Haleakala is a broad summit crater on the island of Maui. Sunrise from the rim looks across a basin of red cinder cones.",
    "Haleakal%C4%81",
  ),
  place(
    "state",
    "hawaii",
    "waimea-canyon",
    "Waimea Canyon",
    -159.665,
    22.073,
    "A deep gorge cuts the west side of Kauai at Waimea Canyon. Red soil and a thin river give the view its color.",
    "Waimea_Canyon_State_Park",
  ),
  place(
    "state",
    "hawaii",
    "uss-arizona",
    "USS Arizona Memorial",
    -157.95,
    21.365,
    "The memorial spans a battleship sunk during the attack on Pearl Harbor. Oil still seeps from the hull beneath the white structure.",
    "USS_Arizona_Memorial",
  ),
  place(
    "state",
    "idaho",
    "craters",
    "Craters of the Moon",
    -113.517,
    43.417,
    "Black lava flows cover a plain at Craters of the Moon. The field looks empty until small plants show in the cracks.",
    "Craters_of_the_Moon_National_Monument_and_Preserve",
  ),
  place(
    "state",
    "idaho",
    "shoshone",
    "Shoshone Falls",
    -114.403,
    42.597,
    "The Snake River drops over a wide ledge near Twin Falls. In a wet spring the falls rank among the largest in the West.",
    "Shoshone_Falls",
  ),
  place(
    "state",
    "idaho",
    "redfish",
    "Redfish Lake",
    -114.918,
    44.145,
    "Redfish Lake sits under the jagged crest of the Sawtooth Mountains. The water near shore is clear enough to show the stony bottom.",
    "Redfish_Lake",
  ),
  place(
    "state",
    "idaho",
    "coeur-dalene",
    "Lake Coeur d'Alene",
    -116.8,
    47.55,
    "A long lake fills a forested valley in the Idaho panhandle. The city of Coeur d'Alene sits at the north end of the water.",
    "Lake_Coeur_d%27Alene",
  ),
  place(
    "state",
    "idaho",
    "city-of-rocks",
    "City of Rocks",
    -113.704,
    42.077,
    "Granite spires rise from a high desert basin near the Utah line. Wagon trains scratched names into these rocks on the California Trail.",
    "City_of_Rocks_National_Reserve",
  ),
  place(
    "state",
    "illinois",
    "willis",
    "Willis Tower",
    -87.636,
    41.879,
    "A black steel tower dominates the Chicago skyline. From the top the view runs across the lake and the flat prairie.",
    "Willis_Tower",
  ),
  place(
    "state",
    "illinois",
    "cahokia",
    "Cahokia Mounds",
    -90.062,
    38.66,
    "Earthen pyramids stand on the Illinois side of the river from Saint Louis. The largest mound was the center of a city that peaked centuries ago.",
    "Cahokia",
  ),
  place(
    "state",
    "illinois",
    "starved-rock",
    "Starved Rock",
    -88.99,
    41.321,
    "A sandstone bluff rises over the Illinois River at Starved Rock. Narrow canyons nearby hold waterfalls after rain and snowmelt.",
    "Starved_Rock_State_Park",
  ),
  place(
    "state",
    "illinois",
    "garden-of-the-gods",
    "Garden of the Gods",
    -88.379,
    37.603,
    "Sandstone hoodoos stand in the Shawnee hills of southern Illinois. The overlook faces forest that runs toward the Ohio River.",
    "Garden_of_the_Gods_Wilderness",
  ),
  place(
    "state",
    "illinois",
    "lincoln-home",
    "Lincoln Home",
    -89.645,
    39.797,
    "Abraham Lincoln's house still stands on a corner in Springfield. The block around it is kept as a nineteenth-century neighborhood.",
    "Lincoln_Home_National_Historic_Site",
  ),
  place(
    "state",
    "indiana",
    "dunes",
    "Indiana Dunes",
    -87.052,
    41.661,
    "Sand dunes rise behind a Lake Michigan beach in northern Indiana. The ridges mark older shorelines left as the lake level fell.",
    "Indiana_Dunes_National_Park",
  ),
  place(
    "state",
    "indiana",
    "monument-circle",
    "Monument Circle",
    -86.158,
    39.768,
    "A limestone soldiers-and-sailors monument stands in a circular street. Downtown Indianapolis was planned to radiate from this one block.",
    "Soldiers%27_and_Sailors%27_Monument_(Indianapolis)",
  ),
  place(
    "state",
    "indiana",
    "brown-county",
    "Brown County State Park",
    -86.228,
    39.147,
    "Forested hills fill Brown County State Park near Nashville. Fall color on these ridges draws crowds down from Indianapolis.",
    "Brown_County_State_Park",
  ),
  place(
    "state",
    "indiana",
    "falls-of-the-ohio",
    "Falls of the Ohio",
    -85.765,
    38.276,
    "A fossil-rich limestone pavement shows at the Falls of the Ohio. The river drops over that shelf between Indiana and Kentucky.",
    "Falls_of_the_Ohio_National_Wildlife_Conservation_Area",
  ),
  place(
    "state",
    "indiana",
    "marengo",
    "Marengo Cave",
    -86.341,
    38.375,
    "Show-cave rooms at Marengo opened to visitors in the late nineteenth century. The passages stay cool while the hills above them change with the seasons.",
    "Marengo_Cave",
  ),
  place(
    "state",
    "iowa",
    "effigy-mounds",
    "Effigy Mounds",
    -91.186,
    43.088,
    "Earthen mounds in animal shapes line wooded bluffs above the Mississippi. The builders left no written record of what the figures meant.",
    "Effigy_Mounds_National_Monument",
  ),
  place(
    "state",
    "iowa",
    "maquoketa",
    "Maquoketa Caves",
    -90.768,
    42.12,
    "A trail links sinkholes and cave passages in a wooded park near Maquoketa. Some rooms open to daylight through collapses in the ceiling.",
    "Maquoketa_Caves_State_Park",
  ),
  place(
    "state",
    "iowa",
    "amana",
    "Amana Colonies",
    -91.871,
    41.8,
    "Seven villages in the Iowa River valley began as a communal society. Workshops and shared kitchens still shape the look of the towns.",
    "Amana_Colonies",
  ),
  place(
    "state",
    "iowa",
    "preparation",
    "Preparation Canyon",
    -95.89,
    41.88,
    "Steep loess ridges rise above the Missouri valley at Preparation Canyon. The hills are windblown silt, and the trails cut sharply into them.",
    "Preparation_Canyon_State_Park",
  ),
  place(
    "state",
    "iowa",
    "field-of-dreams",
    "Field of Dreams",
    -91.133,
    42.498,
    "A baseball diamond was cut into a cornfield near Dyersville for a film. The field stayed after the cameras left, and people still come to play.",
    "Field_of_Dreams",
  ),
  place(
    "state",
    "kansas",
    "monument-rocks",
    "Monument Rocks",
    -100.762,
    38.794,
    "Chalk spires stand on the high plains of western Kansas. Travelers on the Smoky Hill route used them as a landmark.",
    "Monument_Rocks_(Kansas)",
  ),
  place(
    "state",
    "kansas",
    "tallgrass",
    "Tallgrass Prairie",
    -96.559,
    38.434,
    "A remnant of tallgrass prairie is protected in the Flint Hills. Big bluestem on these ridges can grow taller than a person.",
    "Tallgrass_Prairie_National_Preserve",
  ),
  place(
    "state",
    "kansas",
    "cheyenne-bottoms",
    "Cheyenne Bottoms",
    -98.655,
    38.47,
    "A broad wetland basin fills when the creeks and the rains cooperate. Shorebirds stop on these flats in numbers that are hard to count.",
    "Cheyenne_Bottoms",
  ),
  place(
    "state",
    "kansas",
    "castle-rock",
    "Castle Rock",
    -100.172,
    38.861,
    "A chalk pillar and a ring of badlands break the horizon near Quinter. The rock is a leftover of an old inland sea.",
    "Castle_Rock_(Kansas)",
  ),
  place(
    "state",
    "kansas",
    "nicodemus",
    "Nicodemus",
    -99.617,
    39.392,
    "Nicodemus was founded by Black homesteaders after the Civil War. A few historic buildings still mark the townsite on the open prairie.",
    "Nicodemus_National_Historic_Site",
  ),
  place(
    "state",
    "kentucky",
    "mammoth",
    "Mammoth Cave",
    -86.1,
    37.187,
    "The longest known cave system runs under the hills of central Kentucky. Public tours follow only a small piece of the mapped passages.",
    "Mammoth_Cave_National_Park",
  ),
  place(
    "state",
    "kentucky",
    "cumberland-falls",
    "Cumberland Falls",
    -84.599,
    36.837,
    "The Cumberland River drops over a wide ledge in Daniel Boone National Forest. On a clear night with a full moon, a moonbow sometimes forms in the mist.",
    "Cumberland_Falls",
  ),
  place(
    "state",
    "kentucky",
    "red-river",
    "Red River Gorge",
    -83.65,
    37.82,
    "Sandstone arches and cliffs crowd the gorge of the Red River. Climbers and hikers share the trails under the overhangs.",
    "Red_River_Gorge",
  ),
  place(
    "state",
    "kentucky",
    "cumberland-gap",
    "Cumberland Gap",
    -83.673,
    36.604,
    "A low pass through the Cumberland Mountains carried settlers west. The notch is still a walk between steep wooded walls.",
    "Cumberland_Gap",
  ),
  place(
    "state",
    "kentucky",
    "lincoln-birthplace",
    "Abraham Lincoln Birthplace",
    -85.673,
    37.531,
    "A granite memorial shelters a cabin site near Hodgenville. Lincoln's family left this farm while he was still a small child.",
    "Abraham_Lincoln_Birthplace_National_Historical_Park",
  ),
  place(
    "state",
    "louisiana",
    "jackson-square",
    "Jackson Square",
    -90.063,
    29.957,
    "An iron-fenced park sits between the cathedral and the Mississippi levee. Musicians and painters work the walkway in front of the square.",
    "Jackson_Square_(New_Orleans)",
  ),
  place(
    "state",
    "louisiana",
    "avery",
    "Avery Island",
    -91.905,
    29.899,
    "A salt dome rises out of the coastal marsh at Avery Island. A pepper-sauce works and a garden of exotic plants both draw visitors.",
    "Avery_Island_(Louisiana)",
  ),
  place(
    "state",
    "louisiana",
    "poverty-point",
    "Poverty Point",
    -91.407,
    32.637,
    "Massive earthen ridges form a prehistoric monument near Bayou Macon. The builders moved the soil by the basketload thousands of years ago.",
    "Poverty_Point",
  ),
  place(
    "state",
    "louisiana",
    "oak-alley",
    "Oak Alley",
    -90.78,
    30.005,
    "Two rows of live oaks frame the walk to a columned house above the river. The plantation behind the levee grew sugar on the flat ground.",
    "Oak_Alley_Plantation",
  ),
  place(
    "state",
    "louisiana",
    "grand-isle",
    "Grand Isle",
    -89.956,
    29.236,
    "Grand Isle is a barrier island on the edge of Barataria Bay. Storms reshape the beach, and the only road in can flood.",
    "Grand_Isle,_Louisiana",
  ),
  place(
    "state",
    "maine",
    "cadillac",
    "Cadillac Mountain",
    -68.261,
    44.353,
    "Cadillac Mountain is the high point of Acadia and of the United States Atlantic coast. From the granite top, the islands of Frenchman Bay look like stepping stones.",
    "Cadillac_Mountain",
  ),
  place(
    "state",
    "maine",
    "katahdin",
    "Mount Katahdin",
    -68.921,
    45.904,
    "Katahdin is the northern end of the Appalachian Trail and the highest peak in Maine. The tableland above treeline is open to weather that can change in minutes.",
    "Mount_Katahdin",
  ),
  place(
    "state",
    "maine",
    "portland-head",
    "Portland Head Light",
    -70.199,
    43.623,
    "A white lighthouse stands on a rock point at the entrance to Portland Harbor. It is one of the oldest lights still working on this coast.",
    "Portland_Head_Light",
  ),
  place(
    "state",
    "maine",
    "moosehead",
    "Moosehead Lake",
    -69.65,
    45.6,
    "Moosehead is the largest lake in Maine, long and broken by islands. Mount Kineo rises as a cliff straight out of the water.",
    "Moosehead_Lake",
  ),
  place(
    "state",
    "maine",
    "pemaquid",
    "Pemaquid Point Light",
    -69.516,
    43.837,
    "Striped bedrock runs into the sea under Pemaquid Point Light. The tower has marked this rocky point since the early nineteenth century.",
    "Pemaquid_Point_Light",
  ),
  place(
    "state",
    "maryland",
    "fort-mchenry",
    "Fort McHenry",
    -76.58,
    39.263,
    "A star-shaped fort guards the entrance to Baltimore Harbor. A flag over the walls during a bombardment became the subject of the national anthem.",
    "Fort_McHenry",
  ),
  place(
    "state",
    "maryland",
    "naval-academy",
    "United States Naval Academy",
    -76.484,
    38.982,
    "The Naval Academy occupies a waterfront campus in Annapolis. Midshipmen drill on a yard that faces the Severn River.",
    "United_States_Naval_Academy",
  ),
  place(
    "state",
    "maryland",
    "assateague",
    "Assateague Island",
    -75.15,
    38.24,
    "Wild horses graze the marshes and beaches of Assateague Island. The Maryland end of the island is a state park behind the dunes.",
    "Assateague_Island",
  ),
  place(
    "state",
    "maryland",
    "antietam",
    "Antietam",
    -77.745,
    39.475,
    "Antietam Creek runs through a battlefield of cornfields and a sunken road. The fighting here was the bloodiest single day of the Civil War.",
    "Antietam_National_Battlefield",
  ),
  place(
    "state",
    "maryland",
    "deep-creek",
    "Deep Creek Lake",
    -79.3,
    39.5,
    "A long reservoir fills a valley in Maryland's western mountains. Boats fill the coves in summer, and the ridges above hold snow in winter.",
    "Deep_Creek_Lake",
  ),
  place(
    "state",
    "massachusetts",
    "walden",
    "Walden Pond",
    -71.34,
    42.439,
    "A kettle pond in Concord is ringed by the woods Thoreau wrote about. In summer the shore is a busy swimming beach as well as a literary site.",
    "Walden_Pond",
  ),
  place(
    "state",
    "massachusetts",
    "provincetown",
    "Provincetown",
    -70.188,
    42.053,
    "Provincetown curls around the harbor at the tip of Cape Cod. A stone tower on the hill marks the Pilgrims' first landing before they sailed on.",
    "Provincetown,_Massachusetts",
  ),
  place(
    "state",
    "massachusetts",
    "greylock",
    "Mount Greylock",
    -73.166,
    42.637,
    "Mount Greylock is the highest summit in Massachusetts. A stone war memorial on top looks over the Berkshire valleys.",
    "Mount_Greylock",
  ),
  place(
    "state",
    "massachusetts",
    "plymouth-rock",
    "Plymouth Rock",
    -70.662,
    41.958,
    "A granite boulder under a classical portico is honored as the Pilgrims' landing place. The rock is smaller than the legend, and the exact landing is still debated.",
    "Plymouth_Rock",
  ),
  place(
    "state",
    "massachusetts",
    "constitution",
    "USS Constitution",
    -71.057,
    42.373,
    "A wooden frigate from the early republic is docked in the Charlestown Navy Yard. She still sails under her own canvas in Boston Harbor on rare occasions.",
    "USS_Constitution",
  ),
  place(
    "state",
    "michigan",
    "pictured-rocks",
    "Pictured Rocks",
    -86.45,
    46.5,
    "Mineral stains paint the sandstone cliffs along this Lake Superior shore. Waterfalls drop from the forest toward the lake between the colored walls.",
    "Pictured_Rocks_National_Lakeshore",
  ),
  place(
    "state",
    "michigan",
    "sleeping-bear",
    "Sleeping Bear Dunes",
    -86.058,
    44.873,
    "Sand dunes climb the bluffs above Lake Michigan at Sleeping Bear. The perched dunes shift when the wind is strong enough to move them.",
    "Sleeping_Bear_Dunes_National_Lakeshore",
  ),
  place(
    "state",
    "michigan",
    "mackinac",
    "Mackinac Island",
    -84.618,
    45.849,
    "Cars are banned on Mackinac Island, so horses and bicycles share the roads. A limestone fort overlooks the harbor where the straits narrow.",
    "Mackinac_Island",
  ),
  place(
    "state",
    "michigan",
    "isle-royale",
    "Isle Royale",
    -88.9,
    48.0,
    "Isle Royale is a wilderness island in Lake Superior, reached by boat or seaplane. Moose and wolves live here with almost no permanent human neighbors.",
    "Isle_Royale_National_Park",
  ),
  place(
    "state",
    "michigan",
    "lake-of-the-clouds",
    "Lake of the Clouds",
    -89.767,
    46.803,
    "A lake sits in a gorge below an escarpment in the Porcupine Mountains. The view from the cliff is one of the classic sights of the Upper Peninsula.",
    "Porcupine_Mountains",
  ),
  place(
    "state",
    "minnesota",
    "itasca",
    "Lake Itasca",
    -95.17,
    47.193,
    "The Mississippi leaves Lake Itasca as a shallow stream a person can wade. The headwaters park is pine forest and a scatter of other lakes.",
    "Lake_Itasca",
  ),
  place(
    "state",
    "minnesota",
    "split-rock",
    "Split Rock Lighthouse",
    -91.367,
    47.2,
    "A lighthouse stands on a cliff of anorthosite above Lake Superior. It was built after a deadly storm wrecked ships on this unmarked shore.",
    "Split_Rock_Lighthouse",
  ),
  place(
    "state",
    "minnesota",
    "minnehaha",
    "Minnehaha Falls",
    -93.211,
    44.915,
    "Minnehaha Creek drops over a limestone ledge in a Minneapolis park. The falls lent a name to a Longfellow poem set far from this gorge.",
    "Minnehaha_Falls",
  ),
  place(
    "state",
    "minnesota",
    "voyageurs",
    "Voyageurs National Park",
    -92.88,
    48.5,
    "Voyageurs is a maze of lakes along the Canadian border. Travel in the park is mostly by boat, the way the fur traders moved.",
    "Voyageurs_National_Park",
  ),
  place(
    "state",
    "minnesota",
    "pipestone",
    "Pipestone National Monument",
    -96.325,
    44.013,
    "A quarry of soft red stone has been worked at Pipestone for centuries. Indigenous carvers still take the stone from the pits under treaty rights.",
    "Pipestone_National_Monument",
  ),
  place(
    "state",
    "mississippi",
    "vicksburg",
    "Vicksburg National Military Park",
    -90.845,
    32.348,
    "Earthworks and a national cemetery cover the bluffs at Vicksburg. The siege here gave Union forces control of the Mississippi River.",
    "Vicksburg_National_Military_Park",
  ),
  place(
    "state",
    "mississippi",
    "natchez",
    "Natchez",
    -91.403,
    31.56,
    "Natchez sits on a bluff above the Mississippi with a district of antebellum houses. The landing under the hill was once a rough stop for flatboats.",
    "Natchez,_Mississippi",
  ),
  place(
    "state",
    "mississippi",
    "biloxi",
    "Biloxi Lighthouse",
    -88.891,
    30.396,
    "A cast-iron lighthouse stands in the median of a beach highway in Biloxi. It has survived hurricanes that leveled much of the coast around it.",
    "Biloxi_Lighthouse",
  ),
  place(
    "state",
    "mississippi",
    "windsor",
    "Windsor Ruins",
    -91.133,
    31.941,
    "Twenty-three columns are what remain of a mansion near Port Gibson. The house burned, and the columns stayed in the field.",
    "Windsor_Ruins",
  ),
  place(
    "state",
    "mississippi",
    "elvis",
    "Elvis Presley Birthplace",
    -88.68,
    34.259,
    "A small shotgun house in Tupelo is where Elvis Presley was born. The museum beside it covers the years before he left for Memphis.",
    "Elvis_Presley_Birthplace",
  ),
  place(
    "state",
    "missouri",
    "gateway-arch",
    "Gateway Arch",
    -90.185,
    38.625,
    "A stainless-steel arch frames the riverfront in Saint Louis. It marks the city that outfitted travelers heading farther west.",
    "Gateway_Arch_National_Park",
  ),
  place(
    "state",
    "missouri",
    "ha-ha-tonka",
    "Ha Ha Tonka",
    -92.767,
    37.973,
    "A ruined stone castle overlooks a spring and a collapsed sink at Ha Ha Tonka. The water below is a karst basin in the Ozark hills.",
    "Ha_Ha_Tonka_State_Park",
  ),
  place(
    "state",
    "missouri",
    "elephant-rocks",
    "Elephant Rocks",
    -90.654,
    37.653,
    "Rounded granite boulders the size of small buildings sit on a bare dome. A path weaves between them in the Saint Francois Mountains.",
    "Elephant_Rocks_State_Park",
  ),
  place(
    "state",
    "missouri",
    "hannibal",
    "Mark Twain Boyhood Home",
    -91.358,
    39.709,
    "The house where Samuel Clemens grew up still stands in Hannibal. The river town gave him the setting for Tom Sawyer and Huck Finn.",
    "Mark_Twain_Boyhood_Home_%26_Museum",
  ),
  place(
    "state",
    "missouri",
    "shut-ins",
    "Johnson's Shut-Ins",
    -90.84,
    37.54,
    "The Black River squeezes through a maze of dark volcanic rock. Swimmers use the chutes when the water is running at a safe level.",
    "Johnson%27s_Shut-Ins_State_Park",
  ),
  place(
    "state",
    "montana",
    "logan-pass",
    "Logan Pass",
    -113.718,
    48.696,
    "The Going-to-the-Sun Road crosses the Continental Divide at Logan Pass. Snow often keeps the high section closed well into summer.",
    "Logan_Pass",
  ),
  place(
    "state",
    "montana",
    "little-bighorn",
    "Little Bighorn Battlefield",
    -107.427,
    45.57,
    "White markers on a grassy ridge show where Custer's battalion was overrun. The field looks over the Little Bighorn River from the Crow reservation.",
    "Little_Bighorn_Battlefield_National_Monument",
  ),
  place(
    "state",
    "montana",
    "bannack",
    "Bannack",
    -112.998,
    45.161,
    "Bannack is a ghost town of log and brick buildings in a narrow creek valley. It boomed with a gold strike and emptied when the easy ore ran out.",
    "Bannack,_Montana",
  ),
  place(
    "state",
    "montana",
    "flathead",
    "Flathead Lake",
    -114.1,
    47.9,
    "Flathead Lake is a broad body of water left by ice in the northern Rockies. Cherry orchards line parts of the eastern shore.",
    "Flathead_Lake",
  ),
  place(
    "state",
    "montana",
    "missouri-headwaters",
    "Missouri Headwaters",
    -111.505,
    45.927,
    "Three rivers meet near Three Forks and become the Missouri. Lewis and Clark camped at the confluence and named the branches.",
    "Missouri_Headwaters_State_Park",
  ),
  place(
    "state",
    "nebraska",
    "chimney-rock",
    "Chimney Rock",
    -103.348,
    41.704,
    "A clay spire stands over the North Platte. Wagon trains used it to count the days still ahead.",
    "Chimney_Rock_National_Historic_Site",
  ),
  place(
    "state",
    "nebraska",
    "scotts-bluff",
    "Scotts Bluff",
    -103.707,
    41.831,
    "The bluff rises beside the river road. Travelers took the pass at its foot rather than the open prairie.",
    "Scotts_Bluff_National_Monument",
  ),
  place(
    "state",
    "nebraska",
    "carhenge",
    "Carhenge",
    -102.858,
    42.142,
    "Old cars stand in a circle near Alliance in the pattern of a famous stone ring. The sculpture sits in a field with nothing but plains on the horizon.",
    "Carhenge",
  ),
  place(
    "state",
    "nebraska",
    "ashfall",
    "Ashfall Fossil Beds",
    -98.159,
    42.425,
    "Skeletons of rhinos and horses lie where volcanic ash buried a water hole. A barn over the dig lets visitors see the bones still in the ground.",
    "Ashfall_Fossil_Beds",
  ),
  place(
    "state",
    "nebraska",
    "homestead",
    "Homestead National Historical Park",
    -96.834,
    40.288,
    "Restored prairie and a cemetery commemorate the homestead era near Beatrice. One of the first claims under the Homestead Act was filed on this ground.",
    "Homestead_National_Historical_Park",
  ),
  place(
    "state",
    "nevada",
    "red-rock",
    "Red Rock Canyon",
    -115.428,
    36.136,
    "Red sandstone escarpments rise just west of Las Vegas. A scenic drive runs along the base of the cliffs.",
    "Red_Rock_Canyon_National_Conservation_Area",
  ),
  place(
    "state",
    "nevada",
    "valley-of-fire",
    "Valley of Fire",
    -114.532,
    36.441,
    "Aztec sandstone in Valley of Fire is colored a deep red. Petroglyphs mark some of the rock faces in the park.",
    "Valley_of_Fire_State_Park",
  ),
  place(
    "state",
    "nevada",
    "wheeler",
    "Wheeler Peak",
    -114.313,
    38.986,
    "Wheeler Peak is the high point of the Snake Range in Great Basin National Park. Ancient bristlecone pines grow on the ridges below the summit.",
    "Wheeler_Peak_(Nevada)",
  ),
  place(
    "state",
    "nevada",
    "sand-harbor",
    "Sand Harbor",
    -119.93,
    39.197,
    "Granite boulders frame a beach on the Nevada shore of Lake Tahoe. The water is clear, and the Sierra rises across the lake.",
    "Lake_Tahoe%E2%80%93Nevada_State_Park",
  ),
  place(
    "state",
    "nevada",
    "hoover",
    "Hoover Dam",
    -114.737,
    36.016,
    "A concrete arch dam holds back Lake Mead in Black Canyon. The powerhouse at its base still feeds the Southwest electrical grid.",
    "Hoover_Dam",
  ),
  place(
    "state",
    "new-hampshire",
    "washington",
    "Mount Washington",
    -71.304,
    44.271,
    "Mount Washington is famous for some of the worst weather in the East. A cog railway and an auto road both climb to the summit building.",
    "Mount_Washington_(New_Hampshire)",
  ),
  place(
    "state",
    "new-hampshire",
    "flume",
    "Flume Gorge",
    -71.681,
    44.098,
    "A narrow granite gorge channels a brook in Franconia Notch. Boardwalks follow the water between walls that nearly meet overhead.",
    "Flume_Gorge",
  ),
  place(
    "state",
    "new-hampshire",
    "winnipesaukee",
    "Lake Winnipesaukee",
    -71.32,
    43.6,
    "Winnipesaukee is a broad, island-filled lake in central New Hampshire. Cottages ring the bays, and the deep water stays cold into early summer.",
    "Lake_Winnipesaukee",
  ),
  place(
    "state",
    "new-hampshire",
    "monadnock",
    "Mount Monadnock",
    -72.109,
    42.862,
    "Monadnock is an isolated peak with a summit of bare rock. The climb is short enough that the top is crowded on fair weekends.",
    "Mount_Monadnock",
  ),
  place(
    "state",
    "new-hampshire",
    "portsmouth",
    "Portsmouth",
    -70.76,
    43.076,
    "Portsmouth is a seaport at the mouth of the Piscataqua River. Brick warehouses on the old waterfront are shops now, and the naval yard is across the river.",
    "Portsmouth,_New_Hampshire",
  ),
  place(
    "state",
    "new-jersey",
    "wildwood",
    "Wildwood",
    -74.815,
    38.992,
    "A wide beach and a wooden boardwalk define Wildwood on the Jersey Shore. The motel strip behind the dunes is a gallery of midcentury neon.",
    "Wildwood,_New_Jersey",
  ),
  place(
    "state",
    "new-jersey",
    "atlantic-city",
    "Atlantic City",
    -74.424,
    39.355,
    "A boardwalk runs along the ocean in front of the casino hotels. Atlantic City built that kind of walkway, and its street names landed in a famous board game.",
    "Atlantic_City,_New_Jersey",
  ),
  place(
    "state",
    "new-jersey",
    "water-gap",
    "Delaware Water Gap",
    -75.125,
    40.97,
    "The Delaware River cuts a gap through Kittatinny Mountain. The New Jersey side of the notch is a ridge called Mount Tammany.",
    "Delaware_Water_Gap",
  ),
  place(
    "state",
    "new-jersey",
    "batsto",
    "Batsto Village",
    -74.649,
    39.642,
    "An old ironmaking village stands in the pines at Batsto. The furnace is cold, but the mansion and the workers' houses remain.",
    "Batsto_Village,_New_Jersey",
  ),
  place(
    "state",
    "new-jersey",
    "edison",
    "Edison Laboratory",
    -74.238,
    40.784,
    "Thomas Edison ran an invention factory from his laboratory in West Orange. The buildings still hold the machines and the library he used.",
    "Thomas_Edison_National_Historical_Park",
  ),
  place(
    "state",
    "new-mexico",
    "white-sands",
    "White Sands",
    -106.172,
    32.787,
    "Gypsum dunes form a white basin in the Tularosa desert. The sand stays cool underfoot even when the ground around it is hot.",
    "White_Sands_National_Park",
  ),
  place(
    "state",
    "new-mexico",
    "carlsbad",
    "Carlsbad Caverns",
    -104.444,
    32.175,
    "An enormous cave system opens under the Guadalupe Mountains. Visitors walk in through the natural entrance or ride an elevator to the Big Room.",
    "Carlsbad_Caverns_National_Park",
  ),
  place(
    "state",
    "new-mexico",
    "chaco",
    "Chaco Canyon",
    -107.96,
    36.06,
    "Massive stone great houses stand in a dry canyon at Chaco. Some walls and roads line up with the sun and the cardinal directions.",
    "Chaco_Culture_National_Historical_Park",
  ),
  place(
    "state",
    "new-mexico",
    "taos-pueblo",
    "Taos Pueblo",
    -105.547,
    36.439,
    "Adobe apartments rise in stacked blocks at Taos Pueblo. Families still live in parts of a village that has been occupied for centuries.",
    "Taos_Pueblo",
  ),
  place(
    "state",
    "new-mexico",
    "shiprock",
    "Shiprock",
    -108.836,
    36.687,
    "A volcanic neck rises alone from the desert in the Navajo Nation. Radiating dikes look like walls running out from the rock.",
    "Shiprock",
  ),
  place(
    "state",
    "new-york",
    "liberty",
    "Statue of Liberty",
    -74.045,
    40.689,
    "A copper figure of Liberty stands on an island in New York Harbor. The statue was a gift from France and has faced arriving ships since the late nineteenth century.",
    "Statue_of_Liberty",
  ),
  place(
    "state",
    "new-york",
    "niagara",
    "Niagara Falls",
    -79.069,
    43.083,
    "The Niagara River plunges over a cliff between Lake Erie and Lake Ontario. The American falls and the larger horseshoe share one gorge.",
    "Niagara_Falls",
  ),
  place(
    "state",
    "new-york",
    "marcy",
    "Mount Marcy",
    -73.924,
    44.113,
    "Mount Marcy is the highest peak in New York, deep in the High Peaks. The summit is open rock above a forest of spruce and fir.",
    "Mount_Marcy",
  ),
  place(
    "state",
    "new-york",
    "watkins",
    "Watkins Glen",
    -76.871,
    42.377,
    "A gorge trail climbs beside waterfalls cut in shale and sandstone. Stone stairs and bridges follow the creek through the narrows.",
    "Watkins_Glen_State_Park",
  ),
  place(
    "state",
    "new-york",
    "letchworth",
    "Letchworth State Park",
    -78.047,
    42.587,
    "The Genesee River runs through a deep gorge at Letchworth. Three major falls drop inside a park nicknamed the Grand Canyon of the East.",
    "Letchworth_State_Park",
  ),
  place(
    "state",
    "north-carolina",
    "hatteras",
    "Cape Hatteras Lighthouse",
    -75.529,
    35.251,
    "A spiral-striped lighthouse warns ships off the shoals of Cape Hatteras. The tower was moved inland when erosion brought the surf too close.",
    "Cape_Hatteras_Lighthouse",
  ),
  place(
    "state",
    "north-carolina",
    "mitchell",
    "Mount Mitchell",
    -82.265,
    35.765,
    "Mount Mitchell is the highest peak in the eastern United States. A short path leads from the road to a summit that is often in cloud.",
    "Mount_Mitchell",
  ),
  place(
    "state",
    "north-carolina",
    "biltmore",
    "Biltmore Estate",
    -82.549,
    35.54,
    "A French-style chateau sits on a large estate in Asheville. George Vanderbilt built it as a country house, and the gardens are still kept.",
    "Biltmore_Estate",
  ),
  place(
    "state",
    "north-carolina",
    "wright",
    "Wright Brothers National Memorial",
    -75.668,
    36.014,
    "A granite monument marks the dune where the Wright brothers first flew a powered airplane. The field below is the same windy stretch at Kill Devil Hills.",
    "Wright_Brothers_National_Memorial",
  ),
  place(
    "state",
    "north-carolina",
    "chimney-rock",
    "Chimney Rock",
    -82.25,
    35.432,
    "A granite monolith towers over Hickory Nut Gorge. An elevator inside the rock and a trail outside both reach the top.",
    "Chimney_Rock_State_Park",
  ),
  place(
    "state",
    "north-dakota",
    "theodore-roosevelt",
    "Theodore Roosevelt National Park",
    -103.525,
    46.914,
    "Painted badlands and bison herds fill the South Unit near Medora. Theodore Roosevelt ranched in this country before he was president.",
    "Theodore_Roosevelt_National_Park",
  ),
  place(
    "state",
    "north-dakota",
    "knife-river",
    "Knife River Indian Villages",
    -101.386,
    47.354,
    "Earthlodge villages once lined the Knife River near the Missouri. Circular depressions in the grass still show where the houses stood.",
    "Knife_River_Indian_Villages_National_Historic_Site",
  ),
  place(
    "state",
    "north-dakota",
    "fort-lincoln",
    "Fort Abraham Lincoln",
    -100.848,
    46.766,
    "A reconstructed army post and a Mandan earthlodge village share a bluff above the Missouri. Custer rode out from this fort on the way to the Little Bighorn.",
    "Fort_Abraham_Lincoln",
  ),
  place(
    "state",
    "north-dakota",
    "sakakawea",
    "Lake Sakakawea",
    -101.42,
    47.5,
    "Garrison Dam backs the Missouri into a reservoir that runs for many miles. The lake is named for the Shoshone woman who traveled with Lewis and Clark.",
    "Lake_Sakakawea",
  ),
  place(
    "state",
    "north-dakota",
    "buffalo",
    "World's Largest Buffalo",
    -98.699,
    46.889,
    "A concrete buffalo the size of a building stands on a hill in Jamestown. The statue became the symbol of a prairie town on the James River.",
    "World%27s_Largest_Buffalo",
  ),
  place(
    "state",
    "ohio",
    "serpent-mound",
    "Serpent Mound",
    -83.43,
    39.025,
    "An earthen serpent winds along a ridge in southern Ohio. The effigy is best seen from the tower built beside it.",
    "Serpent_Mound",
  ),
  place(
    "state",
    "ohio",
    "old-mans-cave",
    "Old Man's Cave",
    -82.308,
    39.434,
    "A recess cave and a gorge trail are the heart of Hocking Hills. Hemlocks grow in the shade of the sandstone cliffs.",
    "Hocking_Hills_State_Park",
  ),
  place(
    "state",
    "ohio",
    "rock-hall",
    "Rock and Roll Hall of Fame",
    -81.695,
    41.509,
    "A glass pyramid on the Cleveland lakefront houses the Rock and Roll Hall of Fame. The building faces the harbor where the city meets Lake Erie.",
    "Rock_and_Roll_Hall_of_Fame",
  ),
  place(
    "state",
    "ohio",
    "brandywine",
    "Brandywine Falls",
    -81.538,
    41.277,
    "Brandywine Creek drops over a layered shale ledge in Cuyahoga Valley. A boardwalk wraps the plunge pool beside the route of an old canal.",
    "Cuyahoga_Valley_National_Park",
  ),
  place(
    "state",
    "ohio",
    "newark",
    "Newark Earthworks",
    -82.447,
    40.055,
    "Ancient earthen walls form huge geometric enclosures at Newark. The Hopewell culture built the octagon and circle as ceremonial ground.",
    "Newark_Earthworks",
  ),
  place(
    "state",
    "oklahoma",
    "mount-scott",
    "Mount Scott",
    -98.532,
    34.763,
    "Mount Scott is a rounded granite peak in the Wichita Mountains. A road spirals to a summit that looks over bison and longhorn prairie.",
    "Mount_Scott_(Oklahoma)",
  ),
  place(
    "state",
    "oklahoma",
    "tallgrass",
    "Tallgrass Prairie Preserve",
    -96.422,
    36.846,
    "A bison herd grazes one of the largest remaining tallgrass prairies. The preserve spreads across the Osage Hills north of Pawhuska.",
    "Tallgrass_Prairie_Preserve",
  ),
  place(
    "state",
    "oklahoma",
    "memorial",
    "Oklahoma City National Memorial",
    -97.517,
    35.473,
    "Empty chairs line a reflecting pool where a federal building once stood. Each chair marks a person killed in the bombing of nineteen ninety-five.",
    "Oklahoma_City_National_Memorial",
  ),
  place(
    "state",
    "oklahoma",
    "beavers-bend",
    "Beavers Bend",
    -94.682,
    34.135,
    "The Mountain Fork runs clear over rocks in Beavers Bend State Park. Pines close in around a bend of Broken Bow Lake.",
    "Beavers_Bend_Resort_Park",
  ),
  place(
    "state",
    "oklahoma",
    "chickasaw",
    "Chickasaw National Recreation Area",
    -96.97,
    34.503,
    "Cold springs and a creek flow through woods near Sulphur. People have come for this water since the park was called Platt.",
    "Chickasaw_National_Recreation_Area",
  ),
  place(
    "state",
    "oregon",
    "crater-lake",
    "Crater Lake",
    -122.109,
    42.945,
    "A deep blue lake fills the caldera of a collapsed volcano. It is the deepest lake in the United States, and the rim is often under snow.",
    "Crater_Lake",
  ),
  place(
    "state",
    "oregon",
    "multnomah",
    "Multnomah Falls",
    -122.116,
    45.576,
    "A two-tier waterfall drops beside the historic Columbia River highway. A footbridge crosses in front of the lower plunge and a basalt cliff.",
    "Multnomah_Falls",
  ),
  place(
    "state",
    "oregon",
    "haystack",
    "Haystack Rock",
    -123.968,
    45.884,
    "A sea stack stands in the surf at Cannon Beach. Tide pools at its base hold anemones and stars when the water is out.",
    "Haystack_Rock",
  ),
  place(
    "state",
    "oregon",
    "smith-rock",
    "Smith Rock",
    -121.14,
    44.368,
    "A wall of volcanic tuff rises from a bend in the Crooked River. Climbers use the colored faces, and a trail circles the base.",
    "Smith_Rock_State_Park",
  ),
  place(
    "state",
    "oregon",
    "hood",
    "Mount Hood",
    -121.696,
    45.373,
    "A snowy volcano east of Portland shows on the skyline when the sky is clear. Skiers use the slopes, and a timber lodge sits on the south side.",
    "Mount_Hood",
  ),
  place(
    "state",
    "pennsylvania",
    "independence",
    "Independence Hall",
    -75.15,
    39.949,
    "Independence Hall is where delegates debated the Declaration and the Constitution. The brick building faces a square in the oldest part of Philadelphia.",
    "Independence_Hall",
  ),
  place(
    "state",
    "pennsylvania",
    "gettysburg",
    "Gettysburg",
    -77.231,
    39.831,
    "Ridges, fields, and a cemetery mark the battlefield at Gettysburg. Lincoln later spoke at the burial ground on this same ground.",
    "Gettysburg_National_Military_Park",
  ),
  place(
    "state",
    "pennsylvania",
    "fallingwater",
    "Fallingwater",
    -79.468,
    39.906,
    "Frank Lloyd Wright set a house directly over a waterfall in a wooded glen. The stream runs beneath the living room and out past the concrete terraces.",
    "Fallingwater",
  ),
  place(
    "state",
    "pennsylvania",
    "presque-isle",
    "Presque Isle",
    -80.104,
    42.14,
    "A sandy peninsula curves into Lake Erie at Presque Isle. Beaches, lagoons, and a lighthouse share a spit that is still moving.",
    "Presque_Isle_State_Park",
  ),
  place(
    "state",
    "pennsylvania",
    "pine-creek",
    "Pine Creek Gorge",
    -77.356,
    41.573,
    "Pine Creek has cut a deep gorge through the Allegheny Plateau. Overlooks at Leonard Harrison look into the valley called the Grand Canyon of Pennsylvania.",
    "Pine_Creek_Gorge",
  ),
  place(
    "state",
    "rhode-island",
    "breakers",
    "The Breakers",
    -71.298,
    41.45,
    "A Vanderbilt mansion in Newport copies the plan of an Italian palace. The rooms look out over the Atlantic from a lawn above the cliffs.",
    "The_Breakers",
  ),
  place(
    "state",
    "rhode-island",
    "state-house",
    "Rhode Island State House",
    -71.415,
    41.831,
    "A white marble dome is the highest point on the Providence skyline. The capitol stands on a hill above the river that runs through downtown.",
    "Rhode_Island_State_House",
  ),
  place(
    "state",
    "rhode-island",
    "beavertail",
    "Beavertail Lighthouse",
    -71.4,
    41.449,
    "Beavertail Light marks the rocky southern tip of Conanicut Island. Waves break on ledges that have wrecked ships since colonial times.",
    "Beavertail_Lighthouse",
  ),
  place(
    "state",
    "rhode-island",
    "point-judith",
    "Point Judith Light",
    -71.481,
    41.364,
    "Point Judith Light stands where Narragansett Bay opens to the Atlantic. A working harbor sits just behind this low, windy point.",
    "Point_Judith_Light",
  ),
  place(
    "state",
    "rhode-island",
    "slater",
    "Slater Mill",
    -71.383,
    41.877,
    "Slater Mill in Pawtucket is remembered as a starting point of the American textile industry. The old brick buildings stand beside the falls of the Blackstone River.",
    "Slater_Mill_Historic_Site",
  ),
  place(
    "state",
    "south-carolina",
    "sumter",
    "Fort Sumter",
    -79.874,
    32.752,
    "A brick fort on an island in Charleston Harbor is where the Civil War's first shots were fired. The walls are lower now, worn by the long bombardment that followed.",
    "Fort_Sumter",
  ),
  place(
    "state",
    "south-carolina",
    "congaree",
    "Congaree National Park",
    -80.783,
    33.785,
    "Congaree protects a rare stand of old-growth bottomland hardwood. A boardwalk loops through cypress and tupelo that flood when the river rises.",
    "Congaree_National_Park",
  ),
  place(
    "state",
    "south-carolina",
    "harbour-town",
    "Harbour Town",
    -80.81,
    32.14,
    "A red-and-white lighthouse marks the marina at the heel of Hilton Head. Marsh and open sound spread beyond the resort harbor.",
    "Harbour_Town",
  ),
  place(
    "state",
    "south-carolina",
    "table-rock",
    "Table Rock",
    -82.701,
    35.041,
    "Table Rock is a granite mountain that looks flat-topped from the valley. A steep trail climbs to a view across the Blue Ridge.",
    "Table_Rock_State_Park_(South_Carolina)",
  ),
  place(
    "state",
    "south-carolina",
    "myrtle",
    "Myrtle Beach",
    -78.887,
    33.689,
    "A long boardwalk and a wide strand define Myrtle Beach. Hotels and dunes run for miles along this stretch of coast.",
    "Myrtle_Beach,_South_Carolina",
  ),
  place(
    "state",
    "south-dakota",
    "rushmore",
    "Mount Rushmore",
    -103.459,
    43.879,
    "Four presidential faces are carved into a granite peak in the Black Hills. The sculptures are large enough to read from the terrace far below.",
    "Mount_Rushmore",
  ),
  place(
    "state",
    "south-dakota",
    "badlands",
    "Badlands National Park",
    -101.941,
    43.746,
    "Layered buttes and pinnacles form the wall of the Badlands. The soft rock erodes so quickly that the skyline changes within a lifetime.",
    "Badlands_National_Park",
  ),
  place(
    "state",
    "south-dakota",
    "crazy-horse",
    "Crazy Horse Memorial",
    -103.624,
    43.836,
    "A mountain carving of the Lakota leader Crazy Horse is still in progress near Custer. The face is finished, and the figure of the horse is only begun.",
    "Crazy_Horse_Memorial",
  ),
  place(
    "state",
    "south-dakota",
    "jewel-cave",
    "Jewel Cave",
    -103.83,
    43.73,
    "Jewel Cave is a vast maze of passages under the southern Black Hills. Calcite crystals on the walls gave the cave its name.",
    "Jewel_Cave_National_Monument",
  ),
  place(
    "state",
    "south-dakota",
    "corn-palace",
    "Corn Palace",
    -98.026,
    43.713,
    "An arena in Mitchell is redecorated each year with murals made of corn and grain. The pictures change with the harvest, and the onion domes stay.",
    "Corn_Palace",
  ),
  place(
    "state",
    "tennessee",
    "clingmans",
    "Clingmans Dome",
    -83.498,
    35.563,
    "Clingmans Dome is the highest point in the Great Smoky Mountains. A ramp climbs to an observation tower that is often inside a cloud.",
    "Clingmans_Dome",
  ),
  place(
    "state",
    "tennessee",
    "graceland",
    "Graceland",
    -90.023,
    35.047,
    "Graceland is the Memphis mansion where Elvis Presley lived. The rooms are kept much as he left them, including the jungle-themed den.",
    "Graceland",
  ),
  place(
    "state",
    "tennessee",
    "ryman",
    "Ryman Auditorium",
    -86.778,
    36.161,
    "The Ryman in Nashville was the longtime home of the Grand Ole Opry. Wooden pews and brick walls still surround the shows.",
    "Ryman_Auditorium",
  ),
  place(
    "state",
    "tennessee",
    "fall-creek",
    "Fall Creek Falls",
    -85.333,
    35.667,
    "Fall Creek drops over a sandstone ledge into a gorge on the Cumberland Plateau. The falls are among the tallest east of the Rocky Mountains.",
    "Fall_Creek_Falls_State_Park",
  ),
  place(
    "state",
    "tennessee",
    "reelfoot",
    "Reelfoot Lake",
    -89.4,
    36.35,
    "Reelfoot Lake formed when earthquakes dropped a forest into a new basin. Cypress trunks still stand in the water where the woods sank.",
    "Reelfoot_Lake",
  ),
  place(
    "state",
    "texas",
    "alamo",
    "The Alamo",
    -98.486,
    29.426,
    "A Spanish mission church in downtown San Antonio is remembered as a fortress. The battle fought here became a rallying story of the Texas revolution.",
    "Alamo_Mission",
  ),
  place(
    "state",
    "texas",
    "chisos",
    "Chisos Basin",
    -103.301,
    29.275,
    "The Chisos Mountains rise as an island of forest inside the Chihuahuan Desert. The basin at their center is the heart of Big Bend.",
    "Chisos_Mountains",
  ),
  place(
    "state",
    "texas",
    "guadalupe",
    "Guadalupe Peak",
    -104.861,
    31.891,
    "Guadalupe Peak is the highest point in Texas. The trail climbs a limestone reef that was once under a sea and is now a desert mountain.",
    "Guadalupe_Peak",
  ),
  place(
    "state",
    "texas",
    "palo-duro",
    "Palo Duro Canyon",
    -101.667,
    34.983,
    "A deep canyon cuts the high plains of the Texas Panhandle. Red and yellow walls drop from the caprock to a creek on the floor.",
    "Palo_Duro_Canyon",
  ),
  place(
    "state",
    "texas",
    "enchanted-rock",
    "Enchanted Rock",
    -98.819,
    30.506,
    "A pink granite dome rises out of the Texas Hill Country. The rock creaks as it cools after sunset, which earned it a reputation for being alive.",
    "Enchanted_Rock",
  ),
  place(
    "state",
    "utah",
    "delicate-arch",
    "Delicate Arch",
    -109.499,
    38.744,
    "A freestanding sandstone arch is the best-known shape in Arches National Park. The walk to it crosses slickrock with the La Sal Mountains in the distance.",
    "Delicate_Arch",
  ),
  place(
    "state",
    "utah",
    "angels-landing",
    "Angels Landing",
    -112.948,
    37.269,
    "A fin of rock high in Zion Canyon ends at Angels Landing. The last stretch follows a chain along a spine with cliffs on both sides.",
    "Angels_Landing",
  ),
  place(
    "state",
    "utah",
    "bryce",
    "Bryce Canyon",
    -112.167,
    37.628,
    "Pink limestone hoodoos fill the amphitheaters of Bryce Canyon. The formations are the eroded edge of a plateau, not a canyon cut by one river.",
    "Bryce_Canyon_National_Park",
  ),
  place(
    "state",
    "utah",
    "spiral-jetty",
    "Spiral Jetty",
    -112.669,
    41.438,
    "A coil of black basalt curls into the Great Salt Lake at Spiral Jetty. The sculpture vanishes when the lake is high and returns when the water drops.",
    "Spiral_Jetty",
  ),
  place(
    "state",
    "utah",
    "bonneville",
    "Bonneville Salt Flats",
    -113.851,
    40.762,
    "A dry bed of an ancient lake forms a white plain west of the Great Salt Lake. Speed trials use the hard salt when the surface is dry enough to drive.",
    "Bonneville_Salt_Flats",
  ),
  place(
    "state",
    "vermont",
    "mansfield",
    "Mount Mansfield",
    -72.814,
    44.544,
    "Mount Mansfield is the highest summit in Vermont, and its ridge resembles a face. A toll road and a hike both reach the nose of that profile.",
    "Mount_Mansfield",
  ),
  place(
    "state",
    "vermont",
    "burlington",
    "Burlington Waterfront",
    -73.212,
    44.476,
    "Burlington's downtown meets Lake Champlain along a pedestrian waterfront. The Adirondacks show across the water on a clear afternoon.",
    "Burlington,_Vermont",
  ),
  place(
    "state",
    "vermont",
    "bennington",
    "Bennington Battle Monument",
    -73.196,
    42.883,
    "A stone obelisk commemorates a Revolutionary War battle fought near Bennington. It stands on a hill above the town's old brick and wood houses.",
    "Bennington_Battle_Monument",
  ),
  place(
    "state",
    "vermont",
    "quechee",
    "Quechee Gorge",
    -72.41,
    43.637,
    "The Ottauquechee River cuts a narrow gorge through bedrock at Quechee. A highway bridge crosses high above the water, and a trail drops to the river.",
    "Quechee_Gorge",
  ),
  place(
    "state",
    "vermont",
    "camels-hump",
    "Camel's Hump",
    -72.886,
    44.319,
    "Camel's Hump is a double-summited peak in the Green Mountains. The open alpine top is protected, and the trail to it is among the oldest in the state.",
    "Camel%27s_Hump",
  ),
  place(
    "state",
    "virginia",
    "monticello",
    "Monticello",
    -78.453,
    38.009,
    "Thomas Jefferson designed Monticello as a hilltop house above Charlottesville. The dome, the gardens, and the quarters of the enslaved people are all part of the site.",
    "Monticello",
  ),
  place(
    "state",
    "virginia",
    "williamsburg",
    "Colonial Williamsburg",
    -76.693,
    37.271,
    "A restored colonial capital fills several blocks of Williamsburg. Interpreters in period dress work in shops that face the palace green.",
    "Colonial_Williamsburg",
  ),
  place(
    "state",
    "virginia",
    "hawksbill",
    "Hawksbill Mountain",
    -78.395,
    38.556,
    "Hawksbill is the highest peak in Shenandoah National Park. A short spur from the ridge trail reaches a rocky top above the Blue Ridge.",
    "Hawksbill_Mountain",
  ),
  place(
    "state",
    "virginia",
    "mount-vernon",
    "Mount Vernon",
    -77.086,
    38.708,
    "George Washington's house looks over the Potomac from a high bank. The mansion, the outbuildings, and his tomb share the estate he farmed.",
    "Mount_Vernon",
  ),
  place(
    "state",
    "virginia",
    "chincoteague",
    "Chincoteague",
    -75.378,
    37.933,
    "Chincoteague is a fishing town beside the wildlife refuge on Assateague. Ponies from the island are rounded up and auctioned once a year.",
    "Chincoteague,_Virginia",
  ),
  place(
    "state",
    "washington",
    "rainier",
    "Mount Rainier",
    -121.76,
    46.853,
    "A glacier-covered volcano dominates the skyline south of Seattle. The mountain makes its own weather and is often wrapped in cloud.",
    "Mount_Rainier",
  ),
  place(
    "state",
    "washington",
    "hoh",
    "Hoh Rain Forest",
    -123.935,
    47.86,
    "Moss hangs from huge spruce and hemlock in the Hoh Rain Forest. So much rain falls here that the forest floor itself is padded in green.",
    "Hoh_Rain_Forest",
  ),
  place(
    "state",
    "washington",
    "st-helens",
    "Mount St. Helens",
    -122.194,
    46.191,
    "The north flank of Mount Saint Helens collapsed in an eruption that lowered the peak. A crater and a new lava dome now sit where the old summit was.",
    "Mount_St._Helens",
  ),
  place(
    "state",
    "washington",
    "space-needle",
    "Space Needle",
    -122.349,
    47.62,
    "A saucer-shaped deck on a slender tower is a landmark from the Seattle world's fair. It stands beside the museums at Seattle Center.",
    "Space_Needle",
  ),
  place(
    "state",
    "washington",
    "palouse",
    "Palouse Falls",
    -118.185,
    46.596,
    "The Palouse River drops into a rock amphitheater carved by ice-age floods. The canyon below is scabland left when those floodwaters drained.",
    "Palouse_Falls",
  ),
  place(
    "state",
    "west-virginia",
    "new-river",
    "New River Gorge Bridge",
    -81.083,
    38.07,
    "A steel arch carries a highway across the New River Gorge. The bridge is so high that the river and the old town below look small.",
    "New_River_Gorge_Bridge",
  ),
  place(
    "state",
    "west-virginia",
    "shepherdstown",
    "Shepherdstown",
    -77.804,
    39.43,
    "Shepherdstown is a brick river town on the Potomac in the eastern panhandle. Its main street still looks like one of the oldest towns in the state.",
    "Shepherdstown,_West_Virginia",
  ),
  place(
    "state",
    "west-virginia",
    "seneca",
    "Seneca Rocks",
    -79.418,
    38.834,
    "A fin of quartzite stands above the North Fork valley at Seneca Rocks. Climbing routes follow a face that is visible from the highway.",
    "Seneca_Rocks",
  ),
  place(
    "state",
    "west-virginia",
    "blackwater",
    "Blackwater Falls",
    -79.485,
    39.113,
    "Tea-colored water drops at Blackwater Falls in a canyon of dark rock. Hemlock and rhododendron close in along the river below the plunge.",
    "Blackwater_Falls_State_Park",
  ),
  place(
    "state",
    "west-virginia",
    "spruce-knob",
    "Spruce Knob",
    -79.532,
    38.7,
    "Spruce Knob is the highest point in West Virginia. Wind-shaped spruce and a stone lookout mark the summit ridge.",
    "Spruce_Knob",
  ),
  place(
    "state",
    "wisconsin",
    "sea-caves",
    "Mawikwe Bay Sea Caves",
    -91.07,
    46.89,
    "Waves have cut sea caves into the sandstone of the Bayfield Peninsula. In a hard winter the lake ice sometimes lets people walk into those rooms.",
    "Apostle_Islands_National_Lakeshore",
  ),
  place(
    "state",
    "wisconsin",
    "devils-lake",
    "Devil's Lake",
    -89.731,
    43.417,
    "Quartzite bluffs enclose a spring-fed lake in the Baraboo Hills. The cliffs are a classic climb, and the beach fills on hot days.",
    "Devil%27s_Lake_State_Park_(Wisconsin)",
  ),
  place(
    "state",
    "wisconsin",
    "peninsula",
    "Peninsula State Park",
    -87.215,
    45.156,
    "Limestone bluffs and a lighthouse occupy a point of the Door Peninsula. The park looks over the bay from woods and open shoreline.",
    "Peninsula_State_Park",
  ),
  place(
    "state",
    "wisconsin",
    "taliesin",
    "Taliesin",
    -90.07,
    43.141,
    "Frank Lloyd Wright built his home and studio into a hillside near Spring Green. The house burned more than once, and the estate still trains architects.",
    "Taliesin_(studio)",
  ),
  place(
    "state",
    "wisconsin",
    "milwaukee-art",
    "Milwaukee Art Museum",
    -87.897,
    43.039,
    "A white sunshade opens like wings above the Milwaukee lakefront museum. The building sits where downtown meets Lake Michigan.",
    "Milwaukee_Art_Museum",
  ),
  place(
    "state",
    "wyoming",
    "old-faithful",
    "Old Faithful",
    -110.828,
    44.46,
    "Old Faithful is a geyser in Yellowstone that erupts on a rough schedule. People gather on the boardwalk whenever the column of water rises.",
    "Old_Faithful",
  ),
  place(
    "state",
    "wyoming",
    "grand-teton",
    "Grand Teton",
    -110.802,
    43.741,
    "The Grand Teton rises straight from the valley with almost no foothills in front. It is the sharpest summit in a short, steep range.",
    "Grand_Teton",
  ),
  place(
    "state",
    "wyoming",
    "devils-tower",
    "Devils Tower",
    -104.698,
    44.59,
    "A fluted column of igneous rock stands above the Belle Fourche River. The tower is sacred to several Plains nations and a famous rock climb.",
    "Devils_Tower",
  ),
  place(
    "state",
    "wyoming",
    "fort-laramie",
    "Fort Laramie",
    -104.536,
    42.213,
    "Fort Laramie was a military post and a supply stop on the overland trails. Restored buildings stand where the Laramie River meets the North Platte.",
    "Fort_Laramie_National_Historic_Site",
  ),
  place(
    "state",
    "wyoming",
    "fossil-butte",
    "Fossil Butte",
    -110.768,
    41.845,
    "Fossil Butte preserves a lake bed packed with fish fossils from the Eocene. Split layers from the quarry show whole skeletons in the rock.",
    "Fossil_Butte_National_Monument",
  ),
  place(
    "country",
    "united-states",
    "mississippi-river",
    "Mississippi River",
    -90.07,
    35.15,
    "The Mississippi drains most of the land between the Rockies and the Appalachians. At Memphis the channel is already a wide working river on its way to the Gulf.",
    "Mississippi_River",
  ),
  place(
    "country",
    "united-states",
    "rocky-mountains",
    "Rocky Mountains",
    -106.445,
    39.118,
    "The Rocky Mountains are the great cordillera of western North America. Mount Elbert in Colorado is the highest summit of the range inside the United States.",
    "Rocky_Mountains",
  ),
  place(
    "country",
    "united-states",
    "gulf-coast",
    "Gulf Coast",
    -90.07,
    29.25,
    "The Gulf Coast bends from Texas to Florida along a warm inland sea. Marshes, barrier islands, and port cities share this low shore.",
    "Gulf_Coast_of_the_United_States",
  ),
  place(
    "country",
    "united-states",
    "great-lakes",
    "Great Lakes",
    -87.0,
    44.0,
    "The Great Lakes hold about a fifth of the world's surface fresh water. Lake Michigan, lying wholly within the United States, sits near the middle of the chain.",
    "Great_Lakes",
  ),
  place(
    "country",
    "united-states",
    "appalachian-mountains",
    "Appalachian Mountains",
    -82.265,
    35.765,
    "The Appalachians run from Alabama to Maine as a long, worn-down chain. Mount Mitchell in North Carolina is the highest point on that crest.",
    "Appalachian_Mountains",
  ),
  place(
    "country",
    "canada",
    "moraine",
    "Moraine Lake",
    -116.186,
    51.321,
    "Moraine Lake is a turquoise glacial lake under the Valley of the Ten Peaks. Rock flour in the meltwater gives the lake its color.",
    "Moraine_Lake",
  ),
  place(
    "country",
    "canada",
    "horseshoe",
    "Horseshoe Falls",
    -79.075,
    43.079,
    "The Canadian brink at Niagara carries most of the river over a curved cliff. Mist from the plunge pool rises in the gorge in every season.",
    "Horseshoe_Falls",
  ),
  place(
    "country",
    "canada",
    "cn-tower",
    "CN Tower",
    -79.387,
    43.642,
    "The CN Tower is a concrete communications spire on the Toronto skyline. A glass-floored deck looks down on the harbor and the islands.",
    "CN_Tower",
  ),
  place(
    "country",
    "canada",
    "peggys",
    "Peggy's Cove",
    -63.918,
    44.492,
    "A lighthouse sits on bare granite at Peggy's Cove. The village is a few houses on a point that takes the full Atlantic weather.",
    "Peggy%27s_Cove",
  ),
  place(
    "country",
    "canada",
    "frontenac",
    "Chateau Frontenac",
    -71.205,
    46.812,
    "A castle-like hotel crowns the cliff above the Saint Lawrence in Quebec City. Copper roofs make it the landmark of the old walled town.",
    "Ch%C3%A2teau_Frontenac",
  ),
  place(
    "country",
    "mexico",
    "teotihuacan",
    "Teotihuacan",
    -98.844,
    19.692,
    "The Pyramid of the Sun anchors a planned city northeast of modern Mexico City. The avenue through it was already ancient when the Aztecs gave the ruins a name.",
    "Teotihuacan",
  ),
  place(
    "country",
    "mexico",
    "chichen",
    "Chichen Itza",
    -88.568,
    20.684,
    "El Castillo at Chichen Itza is a step pyramid built over an older temple. Near the equinox, shadow on the north stair resembles a serpent descending.",
    "Chichen_Itza",
  ),
  place(
    "country",
    "mexico",
    "palenque",
    "Palenque",
    -92.047,
    17.484,
    "Temples and a palace climb a ridge out of the jungle at Palenque. Carved panels and a royal tomb inside a pyramid made the city famous.",
    "Palenque",
  ),
  place(
    "country",
    "mexico",
    "copper",
    "Copper Canyon",
    -107.828,
    27.523,
    "A chain of canyons cuts the Sierra Tarahumara in northwestern Mexico. The viewpoint at Divisadero looks across several of those gorges at once.",
    "Copper_Canyon",
  ),
  place(
    "country",
    "mexico",
    "monte-alban",
    "Monte Alban",
    -96.768,
    17.043,
    "A leveled hilltop above Oaxaca holds the plazas of Monte Alban. The Zapotec city overlooked the valleys around it for many centuries.",
    "Monte_Alb%C3%A1n",
  ),
  place(
    "country",
    "brazil",
    "christ",
    "Christ the Redeemer",
    -43.21,
    -22.951,
    "A concrete statue of Christ stands on Corcovado above Rio de Janeiro. The figure looks over the bay, the beaches, and the steep neighborhoods below.",
    "Christ_the_Redeemer_(statue)",
  ),
  place(
    "country",
    "brazil",
    "iguacu",
    "Iguacu Falls",
    -54.436,
    -25.695,
    "Hundreds of falls pour over a curved cliff on the Iguacu River. From the Brazilian side the spray hides and reveals the long lip of water.",
    "Igua%C3%A7u_Falls",
  ),
  place(
    "country",
    "brazil",
    "meeting",
    "Meeting of the Waters",
    -59.905,
    -3.14,
    "The dark Rio Negro and the sandy Amazon run side by side for miles near Manaus. They mix slowly because their speed and temperature are different.",
    "Meeting_of_Waters",
  ),
  place(
    "country",
    "brazil",
    "brasilia",
    "Cathedral of Brasilia",
    -47.875,
    -15.798,
    "A ring of curved concrete columns forms the cathedral in Brasilia. The capital around it was planned on open ground and opened in nineteen sixty.",
    "Cathedral_of_Bras%C3%ADlia",
  ),
  place(
    "country",
    "brazil",
    "lencois",
    "Lencois Maranhenses",
    -43.128,
    -2.485,
    "White dunes in Maranhao fill with freshwater lagoons during the rainy months. The pools are rain trapped in the sand, not inlets from the sea.",
    "Len%C3%A7%C3%B3is_Maranhenses_National_Park",
  ),
  place(
    "country",
    "united-kingdom",
    "stonehenge",
    "Stonehenge",
    -1.826,
    51.179,
    "A ring of standing stones rises from Salisbury Plain. The alignment with the solstice sunrise is what people still come to see.",
    "Stonehenge",
  ),
  place(
    "country",
    "united-kingdom",
    "edinburgh",
    "Edinburgh Castle",
    -3.2,
    55.949,
    "A castle occupies a volcanic crag above the old town of Edinburgh. The rock has been fortified for centuries and still holds the Scottish crown jewels.",
    "Edinburgh_Castle",
  ),
  place(
    "country",
    "united-kingdom",
    "causeway",
    "Giant's Causeway",
    -6.511,
    55.241,
    "Basalt columns lock together like a pavement at the Giant's Causeway. The rocks step from the cliff into the sea on the Antrim coast.",
    "Giant%27s_Causeway",
  ),
  place(
    "country",
    "united-kingdom",
    "ben-nevis",
    "Ben Nevis",
    -5.003,
    56.797,
    "Ben Nevis is the highest mountain in the British Isles. The usual path is a long climb, and the summit can be in cloud while the glen is clear.",
    "Ben_Nevis",
  ),
  place(
    "country",
    "united-kingdom",
    "snowdon",
    "Snowdon",
    -4.076,
    53.068,
    "Snowdon is the highest mountain in Wales. A rack railway and several footpaths reach a summit that can see the Irish Sea.",
    "Snowdon",
  ),
  place(
    "country",
    "france",
    "eiffel",
    "Eiffel Tower",
    2.294,
    48.858,
    "An iron lattice tower built for a world's fair became the symbol of Paris. It was meant to be temporary and stayed.",
    "Eiffel_Tower",
  ),
  place(
    "country",
    "france",
    "mont-saint-michel",
    "Mont Saint-Michel",
    -1.511,
    48.636,
    "An abbey crowns a tidal rock off the coast of Normandy. At high tide the water surrounds the causeway that reaches the mount.",
    "Mont-Saint-Michel",
  ),
  place(
    "country",
    "france",
    "chambord",
    "Chateau de Chambord",
    1.517,
    47.616,
    "A royal hunting lodge in the Loire valley is famous for a double-spiral stair. The roof is a crowd of chimneys, lanterns, and turrets above a moat.",
    "Ch%C3%A2teau_de_Chambord",
  ),
  place(
    "country",
    "france",
    "pont-du-gard",
    "Pont du Gard",
    4.535,
    43.949,
    "A Roman aqueduct crosses the Gardon in three stacked rows of arches. It once carried water toward Nimes and still stands as a dry stone bridge.",
    "Pont_du_Gard",
  ),
  place(
    "country",
    "france",
    "mont-blanc",
    "Mont Blanc",
    6.865,
    45.833,
    "Mont Blanc is the highest summit in the Alps. The massif sits on the French-Italian border, and the usual climb starts from Chamonix.",
    "Mont_Blanc",
  ),
  place(
    "country",
    "germany",
    "brandenburg",
    "Brandenburg Gate",
    13.378,
    52.516,
    "A neoclassical gate closes the east end of Unter den Linden in Berlin. It has framed parades, a divided city, and the night the wall opened.",
    "Brandenburg_Gate",
  ),
  place(
    "country",
    "germany",
    "neuschwanstein",
    "Neuschwanstein Castle",
    10.749,
    47.557,
    "A palace in the style of a medieval romance clings to a crag in Bavaria. Ludwig the second built it as a retreat and barely lived there.",
    "Neuschwanstein_Castle",
  ),
  place(
    "country",
    "germany",
    "cologne",
    "Cologne Cathedral",
    6.958,
    50.941,
    "Twin Gothic spires rise over the Rhine in the center of Cologne. Work on the cathedral stretched across centuries and finished in the eighteen hundreds.",
    "Cologne_Cathedral",
  ),
  place(
    "country",
    "germany",
    "zugspitze",
    "Zugspitze",
    10.983,
    47.421,
    "Zugspitze is the highest peak in Germany, on the border with Austria. A cable car and a rack railway both reach the summit ridge.",
    "Zugspitze",
  ),
  place(
    "country",
    "germany",
    "speicherstadt",
    "Speicherstadt",
    9.999,
    53.543,
    "Red-brick warehouses on narrow canals form the Speicherstadt in Hamburg. The district was built as a free port, and the gables still stand over the water.",
    "Speicherstadt",
  ),
  place(
    "country",
    "italy",
    "colosseum",
    "Colosseum",
    12.492,
    41.89,
    "The Colosseum is a huge amphitheater in the center of Rome. Public games once filled the stands that visitors walk today.",
    "Colosseum",
  ),
  place(
    "country",
    "italy",
    "saint-marks",
    "Saint Mark's Basilica",
    12.339,
    45.434,
    "Mosaics cover the interior of Saint Mark's Basilica on Venice's main square. The church faces a plaza that floods when the tide runs high.",
    "St_Mark%27s_Basilica",
  ),
  place(
    "country",
    "italy",
    "duomo",
    "Florence Cathedral",
    11.256,
    43.773,
    "Brunelleschi's red-tiled dome rises over the cathedral of Florence. It was the largest dome yet built when it closed, and it still defines the skyline.",
    "Florence_Cathedral",
  ),
  place(
    "country",
    "italy",
    "etna",
    "Mount Etna",
    14.993,
    37.751,
    "Mount Etna is an active volcano above the east coast of Sicily. Lava and ash keep reshaping the slopes over the orchards.",
    "Mount_Etna",
  ),
  place(
    "country",
    "italy",
    "tre-cime",
    "Tre Cime di Lavaredo",
    12.302,
    46.618,
    "Three limestone towers stand in a row in the Dolomites. A circuit path around their base is one of the most walked routes in the Alps.",
    "Tre_Cime_di_Lavaredo",
  ),
  place(
    "country",
    "egypt",
    "giza",
    "Great Pyramid of Giza",
    31.134,
    29.979,
    "The Great Pyramid is the last of the classical wonders still standing. It rises on a desert plateau at the edge of Cairo, squared to the compass with great care.",
    "Great_Pyramid_of_Giza",
  ),
  place(
    "country",
    "egypt",
    "karnak",
    "Karnak",
    32.657,
    25.718,
    "Karnak is a vast temple precinct on the east bank at Luxor. The columns of the great hypostyle hall still dwarf anyone walking between them.",
    "Karnak",
  ),
  place(
    "country",
    "egypt",
    "abu-simbel",
    "Abu Simbel",
    31.626,
    22.337,
    "Four seated colossi of Ramses the second guard a temple cut into the cliff. The whole monument was moved in the nineteen sixties to escape the rising Nile.",
    "Abu_Simbel",
  ),
  place(
    "country",
    "egypt",
    "sinai",
    "Mount Sinai",
    33.975,
    28.539,
    "A monastery sits at the foot of the peak pilgrims call Mount Sinai. The night climb reaches the summit in time for sunrise over the desert ranges.",
    "Mount_Sinai",
  ),
  place(
    "country",
    "egypt",
    "siwa",
    "Siwa Oasis",
    25.519,
    29.203,
    "Siwa is an oasis of springs and date palms deep in the western desert. Mud-brick ruins and salt lakes surround a town that was once an oracle's seat.",
    "Siwa_Oasis",
  ),
  place(
    "country",
    "india",
    "taj",
    "Taj Mahal",
    78.042,
    27.175,
    "A white marble mausoleum on the Yamuna was built for a Mughal emperor's wife. The tomb, the gardens, and the long reflecting pool are laid out in strict symmetry.",
    "Taj_Mahal",
  ),
  place(
    "country",
    "india",
    "varanasi",
    "Dashashwamedh Ghat",
    83.01,
    25.306,
    "Stone steps at Dashashwamedh Ghat lead down to the Ganges in Varanasi. An evening ceremony of lamps and bells fills the riverfront.",
    "Dashashwamedh_Ghat",
  ),
  place(
    "country",
    "india",
    "hampi",
    "Hampi",
    76.462,
    15.335,
    "Ruins of the Vijayanagara capital spread among boulders at Hampi. Temples and market streets of the old city still stand in the rocks.",
    "Hampi",
  ),
  place(
    "country",
    "india",
    "golden-temple",
    "Golden Temple",
    74.876,
    31.62,
    "The Golden Temple stands on a platform in a sacred pool at Amritsar. The upper floors are sheathed in gold, and the kitchen feeds anyone who arrives.",
    "Golden_Temple",
  ),
  place(
    "country",
    "india",
    "alappuzha",
    "Alappuzha Backwaters",
    76.338,
    9.498,
    "Canals and lagoons thread the coastal plain around Alappuzha. Houseboats move slowly between palms and villages built at the water's edge.",
    "Alappuzha",
  ),
  place(
    "country",
    "china",
    "badaling",
    "Badaling Great Wall",
    116.017,
    40.354,
    "A restored stretch of the Great Wall crosses the ridges at Badaling. Watchtowers step along the crest north of Beijing.",
    "Badaling",
  ),
  place(
    "country",
    "china",
    "forbidden",
    "Forbidden City",
    116.391,
    39.916,
    "The Forbidden City is a walled palace at the center of Beijing. Courtyards and halls line up on the axis that organized the imperial capital.",
    "Forbidden_City",
  ),
  place(
    "country",
    "china",
    "terracotta",
    "Terracotta Army",
    109.273,
    34.385,
    "Thousands of clay soldiers stand in pits east of the first Qin emperor's tomb. The faces were modeled individually, and the army was buried to guard him.",
    "Terracotta_Army",
  ),
  place(
    "country",
    "china",
    "potala",
    "Potala Palace",
    91.117,
    29.658,
    "The Potala climbs a hill above Lhasa in white and red blocks. It was a winter seat of the Dalai Lamas and still dominates the city.",
    "Potala_Palace",
  ),
  place(
    "country",
    "china",
    "yangshuo",
    "Yangshuo",
    110.496,
    24.778,
    "Karst peaks rise straight from the plain along the Li River near Yangshuo. Boats follow the bends between those towers of rock.",
    "Yangshuo",
  ),
  place(
    "country",
    "japan",
    "fuji",
    "Mount Fuji",
    138.727,
    35.361,
    "Mount Fuji is a symmetrical volcano and the highest peak in Japan. On a clear day it shows from Tokyo, and crowds climb it in the short summer season.",
    "Mount_Fuji",
  ),
  place(
    "country",
    "japan",
    "fushimi",
    "Fushimi Inari",
    135.772,
    34.967,
    "Thousands of vermilion gates climb the mountain behind Fushimi Inari in Kyoto. Worshippers donated the torii, and they form tunnels up the slope.",
    "Fushimi_Inari-taisha",
  ),
  place(
    "country",
    "japan",
    "miyajima",
    "Itsukushima Shrine",
    132.319,
    34.296,
    "A great shrine gate stands in the sea off Miyajima when the tide is high. The halls on shore are built on piers so the complex seems to float.",
    "Itsukushima_Shrine",
  ),
  place(
    "country",
    "japan",
    "shiretoko",
    "Shiretoko Five Lakes",
    145.09,
    44.12,
    "Five small lakes sit on a volcanic peninsula in northeastern Hokkaido. Brown bears are common enough here that the boardwalks come with warnings.",
    "Shiretoko_National_Park",
  ),
  place(
    "country",
    "japan",
    "shuri",
    "Shuri Castle",
    127.719,
    26.217,
    "Shuri Castle was the palace of the Ryukyu kings on a hill above Naha. The red halls have been rebuilt after war and fire and remain the symbol of Okinawa.",
    "Shuri_Castle",
  ),
  place(
    "country",
    "australia",
    "opera",
    "Sydney Opera House",
    151.215,
    -33.857,
    "White shell roofs cover the opera house on a point in Sydney Harbour. The building is famous both for that shape and for the long fight to finish it.",
    "Sydney_Opera_House",
  ),
  place(
    "country",
    "australia",
    "uluru",
    "Uluru",
    131.037,
    -25.345,
    "A sandstone monolith stands alone on the desert plain at the center of the continent. The rock changes color with the light, and the base is lined with sacred sites.",
    "Uluru",
  ),
  place(
    "country",
    "australia",
    "whitehaven",
    "Whitehaven Beach",
    149.037,
    -20.282,
    "Pale silica sand curves along Whitsunday Island at Whitehaven Beach. The water over that sand shifts from turquoise in the shallows to deep blue offshore.",
    "Whitehaven_Beach",
  ),
  place(
    "country",
    "australia",
    "apostles",
    "Twelve Apostles",
    143.105,
    -38.662,
    "Limestone stacks stand in the surf along the Great Ocean Road. They are leftovers of cliffs that the Southern Ocean is still cutting away.",
    "The_Twelve_Apostles_(Victoria)",
  ),
  place(
    "country",
    "australia",
    "ubirr",
    "Ubirr",
    132.958,
    -12.41,
    "Rock shelters at Ubirr in Kakadu hold paintings layered across thousands of years. The lookout above them faces a floodplain that turns to water in the wet season.",
    "Ubirr",
  ),
  place(
    "globe",
    "globe",
    "giza",
    "Giza Plateau",
    31.134,
    29.979,
    "Three stone pyramids sit on the desert edge of Cairo. They were already old when the city around them was young.",
    "Giza_pyramid_complex",
  ),
  place(
    "globe",
    "globe",
    "uluru",
    "Uluru",
    131.037,
    -25.345,
    "A sandstone monolith stands in the middle of Australia. The rock is older than the dunes around its base.",
    "Uluru",
  ),
  place(
    "globe",
    "globe",
    "machu",
    "Machu Picchu",
    -72.545,
    -13.163,
    "Stone terraces and temples cling to a ridge above the Urubamba River. The Inca estate was left behind and stayed out of Spanish records.",
    "Machu_Picchu",
  ),
  place(
    "globe",
    "globe",
    "petra",
    "Petra",
    35.449,
    30.328,
    "Facades cut into rose sandstone line a hidden valley in southern Jordan. The treasury appears suddenly at the end of a narrow slot canyon.",
    "Petra",
  ),
  place(
    "globe",
    "globe",
    "angkor",
    "Angkor Wat",
    103.867,
    13.412,
    "A temple mountain of galleries and towers rises inside a wide moat. Bas-reliefs along the walls tell episodes from Hindu epic poems.",
    "Angkor_Wat",
  ),
  place(
    "globe",
    "globe",
    "everest",
    "Mount Everest",
    86.925,
    27.988,
    "Mount Everest is the highest point on Earth, on the Nepal-China border. Routes approach from both sides, and the summit is a narrow crest of snow and rock.",
    "Mount_Everest",
  ),
  place(
    "globe",
    "globe",
    "victoria",
    "Victoria Falls",
    25.858,
    -17.924,
    "The Zambezi drops into a narrow gorge in one broad sheet of water. Spray rises high enough that the falls can be spotted from far off in the wet season.",
    "Victoria_Falls",
  ),
  place(
    "globe",
    "globe",
    "tongariki",
    "Ahu Tongariki",
    -109.277,
    -27.125,
    "Fifteen moai stand in a row on a stone platform at Ahu Tongariki. The statues were toppled and later raised again on the largest ceremonial site of Rapa Nui.",
    "Ahu_Tongariki",
  ),
  place(
    "globe",
    "globe",
    "oia",
    "Oia",
    25.376,
    36.461,
    "Whitewashed rooms stack down a cliff on the rim of a flooded caldera. Sunset at Oia looks across the water toward the other islands of the group.",
    "Oia,_Greece",
  ),
  place(
    "globe",
    "globe",
    "puerto-ayora",
    "Puerto Ayora",
    -90.305,
    -0.741,
    "Puerto Ayora is the main town on Santa Cruz in the Galapagos. The research station nearby still cares for giant tortoises from several islands.",
    "Puerto_Ayora",
  ),
  place(
    "globe",
    "globe",
    "serengeti",
    "Serengeti",
    34.833,
    -2.333,
    "Wildebeest cross the grass plains of the Serengeti in a yearly circuit. The ecosystem runs from wooded hills to the open short-grass sea without a hard edge.",
    "Serengeti",
  ),
  place(
    "globe",
    "globe",
    "gullfoss",
    "Gullfoss",
    -20.121,
    64.327,
    "A broad glacial river drops in two steps into a canyon at Gullfoss. Spray soaks the overlook when the wind blows back up the gorge.",
    "Gullfoss",
  ),
];
